# Generated by Django 4.2.3 on 2023-11-28 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0025_answer_votes_answervote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('about', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.answer')),
                ('user_qusetions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.question')),
                ('user_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.tags')),
            ],
        ),
    ]
