# Generated by Django 5.0 on 2023-12-26 15:22

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/user-default.png', null=True, upload_to='profile_pics/')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_answers', models.ManyToManyField(blank=True, related_name='answered_by', to='pages.answers')),
                ('user_questions', models.ManyToManyField(blank=True, related_name='asked_by', to='pages.questions')),
                ('user_tags', models.ManyToManyField(blank=True, related_name='questions_tag', to='pages.tags')),
            ],
        ),
    ]
