# Generated by Django 4.2.3 on 2023-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_answer_votes_answervote'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_answers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_qusetions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_tags',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_answers',
            field=models.ManyToManyField(to='pages.answer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_qusetions',
            field=models.ManyToManyField(to='pages.question'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_tags',
            field=models.ManyToManyField(to='pages.tags'),
        ),
    ]
