# Generated by Django 4.2.3 on 2023-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_answer_votes_answervote'),
        ('account', '0002_remove_userprofile_user_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_qusetions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_questions',
            field=models.ManyToManyField(blank=True, related_name='asked_by', to='pages.question'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_answers',
            field=models.ManyToManyField(blank=True, related_name='answered_by', to='pages.answer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_tags',
            field=models.ManyToManyField(blank=True, related_name='used_by', to='pages.tags'),
        ),
    ]
