# Generated by Django 4.2.3 on 2023-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userprofile_user_qusetions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/user-default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
