# Generated by Django 4.2.3 on 2023-11-30 15:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
