# Generated by Django 4.2.3 on 2023-11-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('answerToTheQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.question')),
            ],
        ),
    ]
