# Generated by Django 5.0 on 2024-01-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answercomments',
            old_name='comments_user',
            new_name='comment_user',
        ),
    ]
