# Generated by Django 4.2.3 on 2023-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_answer_published_date_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
