# Generated by Django 4.2.3 on 2023-11-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_answer_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='context',
            new_name='answer',
        ),
    ]
