# Generated by Django 4.2.3 on 2023-11-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='User',
            new_name='user',
        ),
    ]
