# Generated by Django 4.2.3 on 2023-11-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
