# Generated by Django 4.2.3 on 2023-11-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_comment_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published_date',
        ),
    ]
