# Generated by Django 4.2.3 on 2023-11-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_comment_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerToTheQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='pages.question'),
        ),
    ]
