# Generated by Django 4.2.3 on 2023-11-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_answer_answertothequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='TAGS', to='pages.tags'),
            preserve_default=False,
        ),
    ]
