# Generated by Django 4.2.3 on 2023-11-23 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0021_remove_question_tags_question_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('PubDate', models.DateTimeField(auto_now_add=True)),
                ('commentQues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.question')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
