# Generated by Django 4.2.3 on 2023-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_quescomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
