# Generated by Django 4.2.3 on 2023-12-05 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0026_answervote_pubdate_vote_pubdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Q', 'Cevap'), ('C', 'Yorum'), ('V', 'Oy')], max_length=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.answer')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.quescomment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.vote')),
            ],
        ),
    ]
