# Generated by Django 4.2.3 on 2023-12-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='vote',
        ),
    ]
